/*
 * generated by Xtext 2.21.0
 */
package dk.sdu.student.shsha15;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MathInterpreterRuntimeModule extends AbstractMathInterpreterRuntimeModule {
}
