/*
 * generated by Xtext 2.21.0
 */
package dk.sdu.student.shsha15;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MathInterpreterStandaloneSetup extends MathInterpreterStandaloneSetupGenerated {

	public static void doSetup() {
		new MathInterpreterStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
