/*
 * generated by Xtext 2.21.0
 */
package dk.sdu.student.shsha15.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MathInterpreterAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("dk/sdu/student/shsha15/parser/antlr/internal/InternalMathInterpreter.tokens");
	}
}
