/**
 * generated by Xtext 2.21.0
 */
package dk.sdu.student.shsha15.mathInterpreter;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Minus</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.student.shsha15.mathInterpreter.MathInterpreterPackage#getMinus()
 * @model
 * @generated
 */
public interface Minus extends Expression
{
} // Minus
