/*
 * generated by Xtext 2.21.0
 */
package dk.sdu.student.shsha15.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMathInterpreterScopeProvider extends DelegatingScopeProvider {
}
